GIT_URL=https://github.com/kirandutt02-alt/postgres
SLACK_CHANNEL_NAME=build-status
ENVIRONMENT=prod
CODE_BASE_PATH=env/prod
ACTION_MESSAGE=PostgreSQL deployment completed
KEEP_APPROVAL_STAGE=true