---
# =============================================================================
# OS-specific values for Debian family (Ubuntu / Debian)
# =============================================================================
postgresql_packages:
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-contrib-{{ postgresql_version }}"
  - "python3-psycopg2"
  - acl

postgresql_service_name: "postgresql@{{ postgresql_version }}-main"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_config_dir: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_bin_dir: "/usr/lib/postgresql/{{ postgresql_version }}/bin"

postgresql_pgdg_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgresql_pgdg_keyring_path: "/usr/share/keyrings/postgresql-archive-keyring.gpg"

postgresql_system_user: postgres
postgresql_system_group: postgres
