GIT_URL               = https://github.com/kirandutt02-alt/postgres.git
SLACK_CHANNEL_NAME    = jenkis-notification
ENVIRONMENT           = dev
CODE_BASE_PATH        = env/dev
ACTION_MESSAGE        = Dev deployment finished
KEEP_APPROVAL_STAGE   = false
