GIT_URL               = https://github.com/kirandutt02-alt/postgres.git
SLACK_CHANNEL_NAME    = jenkis-notification
ENVIRONMENT           = prod
CODE_BASE_PATH        = env/prod
ACTION_MESSAGE        = Pord deployment finished
KEEP_APPROVAL_STAGE   = true
